.\" -*- nroff -*-
.TH UPDATE-USB.USERMAP 8 "Debian Utilities" "DEBIAN"
.SH NAME
update-usb.usermap \- generate hotplug usb.usermap
.SH SYNOPSIS
.B update-usb.usermap
.SH DESCRIPTION
.PP
.I update-usb.usermap
automatically generates usb.usermap. 
.I update-usb.usermap
will be ran automatically when Debian packages that contain usb.usermap
files are installed or removed from the system.
.PP
.I update-usb.usermap
uses the package-supplied usb.usermap entry files (in /usr/lib/hotplug) for
it's information about the usb modules map (but this can be overruled by the
system administrator, see below). If a usb.usermap entry file is executable,
.I update-usb.usermap
execute the usb.usermap entry file, and use it's stdout to generate the 
usb.usermap database.
.RE
.SH FILES
usb.usermap files:
.RS
.I /etc/hotplug/usb.usermap.local
.RS
usb.usermap files added by the system administrator. 
.RE
.I /usr/lib/hotplug/*/user.usermap
.RS
usb.usermap files provided by other Debian packages.
.RE
.SH AUTHOR 
Fumitoshi UKAI <ukai@debian.or.jp> wrote this program.
.SH "SEE ALSO"
.BR hotplug (8),
.BR /usr/share/doc/hotplug

